/**
 * Vercel 배포 시 BACKEND_URL 환경 변수로 /api → Render(또는 공개 백엔드) 프록시 설정.
 * 정적 파일(frontend/)은 그대로 두고 vercel.json만 생성한다.
 * TMAP_APP_KEY가 있으면 frontend/tmap-key.js 에 주입한다(지도 SDK용).
 */
const fs = require("fs");
const path = require("path");

// Vercel Environment Variables의 BACKEND_URL 사용.
// 비어 있으면 이 프로젝트 기본 Render URL로 폴백 (연결 누락 방지).
const DEFAULT_BACKEND = "https://kids-safe-route-api.onrender.com";
const backend = (process.env.BACKEND_URL || DEFAULT_BACKEND).replace(/\/$/, "");
const root = path.join(__dirname, "..");
const frontendDir = path.join(root, "frontend");

const config = {
  version: 2,
  outputDirectory: "frontend",
  rewrites: [
    {
      source: "/api/:path*",
      destination: `${backend}/api/:path*`,
    },
  ],
};

if (process.env.BACKEND_URL) {
  console.log("[build-vercel] API 프록시 →", backend, "(BACKEND_URL)");
} else {
  console.log(
    "[build-vercel] API 프록시 →",
    backend,
    "(기본값 — Vercel에 BACKEND_URL을 넣으면 그 주소로 바뀝니다)"
  );
}

fs.writeFileSync(path.join(root, "vercel.json"), JSON.stringify(config, null, 2) + "\n");

const tmapKey = (process.env.TMAP_APP_KEY || process.env.TMAP_WEB_APP_KEY || "").trim();
const keyFile = path.join(frontendDir, "tmap-key.js");
// 환경변수가 있을 때만 덮어쓴다. 비어 있으면 저장소의 frontend/tmap-key.js 를 그대로 둔다.
if (tmapKey) {
  let keyJs =
    `// generated by scripts/build-vercel.js — do not edit on Vercel output\n` +
    `window.__TMAP_APP_KEY__ = ${JSON.stringify(tmapKey)};\n` +
    `if (!(window.Tmapv2 && typeof window.Tmapv2.Map === "function")) {\n` +
    `  document.write("<script data-tmap-sdk='1' src='https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey="` +
    ` + encodeURIComponent(window.__TMAP_APP_KEY__) + "'><\\/script>");\n` +
    `}\n`;
  fs.writeFileSync(keyFile, keyJs);
  console.log(`[build-vercel] tmap-key.js → TMAP key + sync jsv2 (len=${tmapKey.length})`);
} else {
  console.log(
    "[build-vercel] tmap-key.js unchanged (set TMAP_APP_KEY on Vercel to override repo file)"
  );
}
