/**
 * Vercel 배포 시 BACKEND_URL 환경 변수로 /api → Render(또는 공개 백엔드) 프록시 설정.
 * TMAP_APP_KEY는 빌드 시 frontend/tmap-key.js 에만 주입 (Git에는 넣지 않음).
 */
const fs = require("fs");
const path = require("path");

const DEFAULT_BACKEND = "https://kids-safe-route-api.onrender.com";
const backend = (process.env.BACKEND_URL || DEFAULT_BACKEND).replace(/\/$/, "");
const root = path.join(__dirname, "..");
const frontendDir = path.join(root, "frontend");

const config = {
  version: 2,
  outputDirectory: "frontend",
  rewrites: [
    {
      source: "/api/:path*",
      destination: `${backend}/api/:path*`,
    },
    {
      source: "/g",
      destination: "/kid-guide.html",
    },
  ],
};

if (process.env.BACKEND_URL) {
  console.log("[build-vercel] API 프록시 →", backend, "(BACKEND_URL)");
} else {
  console.log(
    "[build-vercel] API 프록시 →",
    backend,
    "(기본값 — Vercel에 BACKEND_URL을 넣으면 그 주소로 바뀝니다)"
  );
}

fs.writeFileSync(path.join(root, "vercel.json"), JSON.stringify(config, null, 2) + "\n");

const tmapKey = (process.env.TMAP_APP_KEY || process.env.TMAP_WEB_APP_KEY || "").trim();
const keyFile = path.join(frontendDir, "tmap-key.js");
const keyJs =
  `// generated by scripts/build-vercel.js — do not commit\n` +
  `window.__TMAP_APP_KEY__ = window.__TMAP_APP_KEY__ || ${JSON.stringify(tmapKey)};\n` +
  `const tmapAlreadyInjected = document.querySelector('script[data-tmap-sdk="1"]');\n` +
  `if (window.__TMAP_APP_KEY__ && !tmapAlreadyInjected && !(window.Tmapv2 && typeof window.Tmapv2.Map === "function")) {\n` +
  `  document.write("<script data-tmap-sdk='1' src='https://apis.openapi.sk.com/tmap/jsv2?version=1&appKey="` +
  ` + encodeURIComponent(window.__TMAP_APP_KEY__) + "'><\\/script>");\n` +
  `}\n`;
fs.writeFileSync(keyFile, keyJs);
if (tmapKey) {
  console.log(`[build-vercel] tmap-key.js 생성 (TMAP_APP_KEY len=${tmapKey.length})`);
} else {
  console.log("[build-vercel] tmap-key.js 생성 (키 없음 — Render /api/tmap-bootstrap.js 또는 Vercel TMAP_APP_KEY 사용)");
}
